apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitbucket-var-pvc
  namespace: atlassian
  labels:
    name: bitbucket-var-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: rook-ceph-block
