apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitbucket-srv
  namespace: atlassian
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitbucket
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bitbucket
        track: staging
    spec:
      containers:
      - name: bitbucket-srv
        image: atlassian/bitbucket-server:7.1.1-jdk11
        env:
        # Memory / Heap Size => We are using default min/max memory, no need to set it
        #- name: JVM_MINIMUM_MEMORY
        #  value: 512m
        #- name: JVM_MAXIMUM_MEMORY
        #  value: 1024m
        # Database
        #- name: ATL_JDBC_URL
        #  value: jdbc:mysql://atlassian-db/staging_bitbucket?useUnicode=true&amp;amp;characterEncoding=UTF8&amp;amp;sessionVariables=default_storage_engine=InnoDB
        #- name: ATL_JDBC_USER
        #  value: bitbucket
        #- name: ATL_JDBC_PASSWORD
        #  value: 4tlass14n!
        #- name: ATL_DB_DRIVER
        #  value: com.mysql.jdbc.Driver
        #- name: ATL_DB_TYPE
        #  value: mysql
        # Reverse Proxy Settings
        - name: ATL_PROXY_NAME
          value: bitbucket.k8s-demo.cengn.ca
        - name: ATL_PROXY_PORT
          value: "443"
        - name: ATL_TOMCAT_SCHEME
          value: https
        - name: ATL_TOMCAT_SECURE
          value: "true"
        volumeMounts:
        - name: bitbucket-var
          mountPath: /var/atlassian/application-data/bitbucket
        - name: jdbc-driver-mysql-5148
          mountPath: /var/atlassian/application-data/bitbucket/lib/mysql-connector-java-5.1.48.jar
          subPath: mysql-connector-java-5.1.48.jar

      volumes:
        - name: bitbucket-var
          persistentVolumeClaim:
            claimName: bitbucket-var-pvc
        - name: jdbc-driver-mysql-5148
          configMap:
            name: jdbc-driver-mysql-5148
