apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: redis
  namespace: netbox-flux
  annotations:
    fluxcd.io/automated: "true"
spec:
  chart:
    git: ssh://git@bitbucket.cengn.ca:7999/flux/netbox-flux.git
    path: charts-redis
    ref: master
