namespace: atlassian-flux
resources:
  - namespace.yaml
  - rbac.yaml
  - psp.yaml
  - ssh-config.yaml
  - redis-helm.yaml
  - postgresql-helm.yaml
bases:
  - ../../base/flux/
patchesStrategicMerge:
  - flux-patch.yaml
configMapGenerator:
  - name: flux-kube-config
    behavior: replace
    files:
      - kubeconfig.yaml
