apiVersion: apps/v1
kind: Deployment
metadata:
  name: jira-srv
  namespace: atlassian
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jira
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jira
        track: production
    spec:
      nodeSelector:
        workerClass: infra
      containers:
      - name: jira-srv
        image: atlassian/jira-software:8.11.0-jdk11
        env:
        # JVM configurations (setenv.sh)
        - name: JVM_MINIMUM_MEMORY
          value: 1024m
        - name: JVM_MAXIMUM_MEMORY
          value: 8192m
        - name: JVM_SUPPORT_RECOMMENDED_ARGS
          value: "-XX:+UseCodeCacheFlushing -XX:ReservedCodeCacheSize=512m -XX:+ExplicitGCInvokesConcurrent -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/atlassian/application-data/jira/logs/heapdump/java_pid%p.hprof -Djava.util.prefs.userRoot=/home/jira -Duser.timezone=America/Toronto"
        - name: GC_JVM_PARAMETERS
          value: "-XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+PrintGCCause -Xloggc:$LOGBASEABS/logs/atlassian-jira-gc-%t.log -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=20M ${GC_JVM_PARAMETERS}"
        - name: CATALINA_OPTS
          value: "-Djava.rmi.server.hostname=jira-service -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.rmi.port=9010 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"
        # Database
        - name: ATL_JDBC_URL
          value: jdbc:mysql://atlassian-db/prod_jira?useUnicode=true&amp;amp;characterEncoding=UTF8&amp;amp;sessionVariables=default_storage_engine=InnoDB
        - name: ATL_JDBC_USER
          value: jira
        - name: ATL_JDBC_PASSWORD
          value: $1$uDFN0V14$Jpmyr52RhF8xQNdM4p8Dl0
        - name: ATL_DB_DRIVER
          value: com.mysql.jdbc.Driver
        - name: ATL_DB_TYPE
          value: mysql
        - name: ATL_DB_MINEVICTABLEIDLETIMEMILLIS
          value: "60000"
        - name: ATL_DB_VALIDATIONQUERYTIMEOUT
          value: "3"
        # Reverse Proxy Settings
        - name: ATL_PROXY_NAME
          value: jira.cengn.ca
        - name: ATL_PROXY_PORT
          value: "443"
        - name: ATL_TOMCAT_SCHEME
          value: https
        - name: ATL_TOMCAT_SECURE
          value: "true"
        volumeMounts:
        - name: jira-var
          mountPath: /var/atlassian/application-data/jira
        - name: jdbc-driver-mysql-5148
          mountPath: /opt/atlassian/jira/lib/mysql-connector-java-5.1.48.jar
          subPath: mysql-connector-java-5.1.48.jar
        #- name: conf-backup
        #  mountPath: /var/lib/backups

      volumes:
        #- name: conf-backup
        #  nfs:
        #    path: /mnt/jabbapool1/AtlassianBackup/jira
        #    server: d-stor01.infra.kan.cengn.ca
        - name: jira-var
          persistentVolumeClaim:
            claimName: jira-var-pvc
        - name: jdbc-driver-mysql-5148
          configMap:
            name: jdbc-driver-mysql-5148
